In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_style("whitegrid")
df = pd.read_csv("d:\python\stock_dataset_dirty.csv")

df.head()

<>:6: SyntaxWarning: invalid escape sequence '\p'
<>:6: SyntaxWarning: invalid escape sequence '\p'
C:\Users\momin\AppData\Local\Temp\ipykernel_6604\1370075004.py:6: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv("d:\python\stock_dataset_dirty.csv")

,Date,Symbol,Open,High,Low,Close,Volume,Market_Cap,Sector,Profit_Margin
0,2023-01-01,AMZN,472.847313,395.110972,123.867217,312.916750,428910,2.563560,Retail,13.505575
1,2023-01-02,TSLA,326.053273,134.194156,340.825590,141.306004,969485,1.968346,Finance,26.398130
2,2023-01-03,GOOGL,378.660330,133.858975,482.565246,169.009551,255063,2.588029,Energy,15.866954
3,2023-01-04,TSLA,468.999752,109.903932,170.092522,327.189719,887733,2.152978,Tech,9.820990
4,2023-01-05,TSLA,382.895454,492.383066,408.075071,218.543045,783970,1.684139,Tech,9.777641

In [3]:
df.shape
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           1020 non-null   str
 1   Symbol         1020 non-null   str
 2   Open           1000 non-null   float64
 3   High           1000 non-null   float64
 4   Low            1020 non-null   float64
 5   Close          1020 non-null   float64
 6   Volume         1020 non-null   int64
 7   Market_Cap     1020 non-null   float64
 8   Sector         1020 non-null   str
 9   Profit_Margin  1020 non-null   float64
dtypes: float64(6), int64(1), str(3)
memory usage: 79.8 KB

,Open,High,Low,Close,Volume,Market_Cap,Profit_Margin
count,1000.000000,1000.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,300.574438,306.702771,292.686486,296.245551,546374.051961,1.992106,17.087029
std,117.130249,117.643386,113.889313,114.439984,265163.624615,0.575427,7.115731
min,101.852809,105.054551,95.004596,100.012288,100363.000000,1.007837,5.006025
25%,194.666214,210.026772,192.764438,199.247649,316728.750000,1.486922,10.966898
50%,303.377972,307.228008,294.700725,293.419365,533572.000000,1.987401,16.994874
75%,400.259805,410.192374,391.404735,391.815112,784707.000000,2.481606,22.924993
max,499.765490,509.330742,489.825293,499.099756,998704.000000,2.998921,29.972617

In [4]:
df["Date"] = pd.to_datetime(df["Date"])
df= df.sort_values("Date")
df.head()

,Date,Symbol,Open,High,Low,Close,Volume,Market_Cap,Sector,Profit_Margin
0,2023-01-01,AMZN,472.847313,395.110972,123.867217,312.916750,428910,2.563560,Retail,13.505575
1000,2023-01-01,AMZN,472.847313,395.110972,123.867217,312.916750,428910,2.563560,Retail,13.505575
1001,2023-01-02,TSLA,326.053273,134.194156,340.825590,141.306004,969485,1.968346,Finance,26.398130
1,2023-01-02,TSLA,326.053273,134.194156,340.825590,141.306004,969485,1.968346,Finance,26.398130
2,2023-01-03,GOOGL,378.660330,133.858975,482.565246,169.009551,255063,2.588029,Energy,15.866954

In [5]:
df.isnull().sum()

Date              0
Symbol            0
Open             20
High             20
Low               0
Close             0
Volume            0
Market_Cap        0
Sector            0
Profit_Margin     0
dtype: int64

In [7]:
df.duplicated().sum()

df = df.drop_duplicates()
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Day_Name'] = df['Date'].dt.day_name()

df.head()

,Date,Symbol,Open,High,Low,Close,Volume,Market_Cap,Sector,Profit_Margin,Year,Month,Day,Day_Name
0,2023-01-01,AMZN,472.847313,395.110972,123.867217,312.916750,428910,2.563560,Retail,13.505575,2023,1,1,Sunday
1001,2023-01-02,TSLA,326.053273,134.194156,340.825590,141.306004,969485,1.968346,Finance,26.398130,2023,1,2,Monday
2,2023-01-03,GOOGL,378.660330,133.858975,482.565246,169.009551,255063,2.588029,Energy,15.866954,2023,1,3,Tuesday
3,2023-01-04,TSLA,468.999752,109.903932,170.092522,327.189719,887733,2.152978,Tech,9.820990,2023,1,4,Wednesday
4,2023-01-05,TSLA,382.895454,492.383066,408.075071,218.543045,783970,1.684139,Tech,9.777641,2023,1,5,Thursday

In [ ]:
# Average Closing Price by Company
group_symbol = df.groupby("Symbol")["Close"].mean()

print(group_symbol)

NameError: name 'df' is not defined