In [4]:
import numpy as np 
import pandas as pd
dfcus=pd.read_csv("D:\python\customers.csv")
dfsales=pd.read_csv("d:\python\sales.csv")
print (df)

     order_id        date region   product     category customer_type  \
0           1  2024-04-12   East    Laptop  Electronics     Returning
1           2  2024-12-14  South   Monitor  Accessories     Returning
2           3  2024-09-27  North     Phone  Accessories           New
3           4  2024-04-16   West     Mouse  Electronics     Returning
4           5  2024-03-12   West     Phone  Electronics     Returning
..        ...         ...    ...       ...          ...           ...
495       496  2024-11-20  South     Mouse  Accessories     Returning
496       497  2024-01-04  North     Phone  Accessories     Returning
497       498  2024-01-16  South  Keyboard  Electronics     Returning
498       499  2024-10-06  North     Phone  Accessories     Returning
499       500  2024-12-01  North   Monitor  Electronics           New

     quantity  price  discount    sales
0           8    590      0.09  4295.20
1           2    262      0.18   429.68
2           5    512      0.09  2329.60
3           1    485      0.09   441.35
4           7    332      0.22  1812.72
..        ...    ...       ...      ...
495         6    314      0.23  1450.68
496         9    369      0.23  2557.17
497         6    722      0.14  3725.52
498         2   1449      0.12  2550.24
499         2    869      0.09  1581.58

[500 rows x 10 columns]

<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:3: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
C:\Users\momin\AppData\Local\Temp\ipykernel_8792\988737030.py:3: SyntaxWarning: invalid escape sequence '\p'
  dfcus=pd.read_csv("D:\python\customers.csv")
C:\Users\momin\AppData\Local\Temp\ipykernel_8792\988737030.py:4: SyntaxWarning: invalid escape sequence '\p'
  dfsales=pd.read_csv("d:\python\sales.csv")

In [5]:
dfcus

     order_id  customer_rating
0           1                1
1           2                1
2           3                2
3           4                1
4           5                4
..        ...              ...
495       496                3
496       497                4
497       498                4
498       499                1
499       500                1

[500 rows x 2 columns]

In [6]:
dfcus.head()

   order_id  customer_rating
0         1                1
1         2                1
2         3                2
3         4                1
4         5                4

In [7]:
dfsales

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [8]:
dfsales.head()

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72

In [9]:
dfsales.columns

Index(['order_id', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'discount', 'sales'],
      dtype='str')

In [10]:
dfsales.shape

(500, 10)

In [11]:
dfsales.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    int64
 1   date           500 non-null    str
 2   region         500 non-null    str
 3   product        500 non-null    str
 4   category       500 non-null    str
 5   customer_type  500 non-null    str
 6   quantity       500 non-null    int64
 7   price          500 non-null    int64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: float64(2), int64(3), str(5)
memory usage: 39.2 KB

In [12]:
dfsales.customer_type.value_counts()

customer_type
Returning    261
New          239
Name: count, dtype: int64

In [13]:
dfcus.customer_rating

0      1
1      1
2      2
3      1
4      4
      ..
495    3
496    4
497    4
498    1
499    1
Name: customer_rating, Length: 500, dtype: int64

In [15]:
dfcus .value_counts()

order_id  customer_rating
1         1                  1
2         1                  1
3         2                  1
4         1                  1
5         4                  1
                            ..
496       3                  1
497       4                  1
498       4                  1
499       1                  1
500       1                  1
Name: count, Length: 500, dtype: int64

In [16]:
dfsales.category.value_counts

<bound method IndexOpsMixin.value_counts of 0      Electronics
1      Accessories
2      Accessories
3      Electronics
4      Electronics
          ...
495    Accessories
496    Accessories
497    Electronics
498    Accessories
499    Electronics
Name: category, Length: 500, dtype: str>

In [17]:
dfsales.isnull().sum()

order_id         0
date             0
region           0
product          0
category         0
customer_type    0
quantity         0
price            0
discount         0
sales            0
dtype: int64

In [18]:
dfsales.duplicated().sum()

np.int64(0)

In [19]:
dfsales.describe(include='all')

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
count,500.000000,500,500,500,500,500,500.000000,500.000000,500.00000,500.000000
unique,NaN,267,4,6,2,2,NaN,NaN,NaN,NaN
top,NaN,2024-04-08,North,Mouse,Electronics,Returning,NaN,NaN,NaN,NaN
freq,NaN,6,151,96,266,261,NaN,NaN,NaN,NaN
mean,250.500000,NaN,NaN,NaN,NaN,NaN,4.968000,768.158000,0.14666,3333.059560
std,144.481833,NaN,NaN,NaN,NaN,NaN,2.569081,404.010497,0.08612,2693.185995
min,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000,50.000000,0.00000,67.320000
25%,125.750000,NaN,NaN,NaN,NaN,NaN,3.000000,432.750000,0.08000,1120.867500
50%,250.500000,NaN,NaN,NaN,NaN,NaN,5.000000,742.000000,0.15000,2582.805000
75%,375.250000,NaN,NaN,NaN,NaN,NaN,7.000000,1094.500000,0.22000,4998.030000
max,500.000000,NaN,NaN,NaN,NaN,NaN,9.000000,1499.000000,0.30000,12700.800000